version: '3.4'

services:
  gestiongastosbackend:
    image: gestiongastosbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env  
    ports:
      - 3000:3000
      - 3005:3005
      - 8080:8080
